config/routes.rb
Mobile::Application.routes.draw do

  get "home/index"

  resources :products do
    collection do 
      get 'index'
      get 'show'
   end
  end
  match "products/:category_id" => "products#index"
  

  root :to => "home#index"
  match "search" => "home#search"
  

end

app/models/category.rb
# -*- coding: utf-8 -*-
class Category < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name, :message => 'Podaj nazwę kategori'

  has_many :products
end

app/models/product.rb
# -*- coding: utf-8 -*-

class Product < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  attr_accessible :name, :description, :count, :price, :category

  validates_presence_of :name, :message => 'Podaj nazwę produktu'
  validates_presence_of :description, :message => 'Podaj opis produktu'

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
  end

  def search
    if params[:keyword].present?
      @products = Product.search(params[:keyword])
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.where(:category_id => params[:category_id])
  end

  def show
    begin
      @product = Product.find(params[:id])
    rescue
      redirect_to home_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/_search.html.erb
<%= form_tag('/search') do |f| %>
  <input type="search" name="keyword" placeholder="search for items" />
  <br/>
  <%= submit_tag 'Szukaj' %>
<% end %>

app/views/home/index.html.erb
<%= render :partial => 'search' %>
<% @categories.each do |category| %>
  <div class="category">
    <%= link_to image_tag('category.jpg', :size => '100x100'), products_path(:category_id => category.id) %>
    <%= link_to category.name, products_path(:category_id => category.id) %>
  </div>
  
<% end %>

app/views/home/search.html.erb
<%= render :partial => 'search' %>
<% if @products.present? %>
<ul>
<% @products.each do |product| %>
  <li><%= render :partial => '/products/list_item', :locals => {:product => product} %></li>
<% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile</title>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no" />
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div data-role="page">
    <div data-role="header">
      <h1><a href="/">HOME</a></h1>
      <%= yield :head %>
    </div>
    <div data-role="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/products/_list_item.html.erb
<%= link_to product.name, product_path(product.id) %>

app/views/products/index.html.erb
<h1>Our products</h1>

<% @products.each do |product| %>
  <%= render :partial => 'list_item', :locals => {:product => product} %>
  <br />
<% end %>

app/views/products/show.html.erb
<% content_for :head do %>
<h1><%= @product.name %></h1>
<% end %>
<br/>
<div data-role="collapsible" data-content-theme="c">
   <h3>Sprawdź dostępność</h3>
   <p>W magazynie jest <%= @product.count %>szt</p>
</div>

<div data-role="collapsible" data-content-theme="c">
   <h3>Opis</h3>
   <p><%= @product.description %></p>
</div>